version: "3"
services:
  api:
    build:
      context: ./api/
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
  client:
    build:
      context: ./client/
    depends_on:
      - api
    ports:
      - "80:80"
