.PHONY: clean All

All:
	@echo "----------Building project:[ TD6 - Debug ]----------"
	@cd "td6-algo" && "$(MAKE)" -f  "TD6.mk"
clean:
	@echo "----------Cleaning project:[ TD6 - Debug ]----------"
	@cd "td6-algo" && "$(MAKE)" -f  "TD6.mk" clean
