.PHONY: clean All

All:
	@echo "----------Building project:[ TD8_9 - Debug ]----------"
	@cd "td8-9-c" && "$(MAKE)" -f  "TD8_9.mk"
clean:
	@echo "----------Cleaning project:[ TD8_9 - Debug ]----------"
	@cd "td8-9-c" && "$(MAKE)" -f  "TD8_9.mk" clean
